import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div className='hero'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' type='image/svg+xml' href='/favicon.svg' />
      </Head>
      <nav>
        <Image src='/omencss.svg' alt='OmenCSS Logo' width={100} height={20} id='logo' />
      </nav>
      <main>
        <div className='center'>
          <h1 className='slide-top'>Writing CSS reimagined</h1>
        </div>
        <div className='sticky'>
          <div className='bubbles'>
            <div className='bubble' />
            <div className='bubble' />
            <div className='bubble' />
          </div>
        </div>
      </main>
    </div>
  )
}
