import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' type='image/svg+xml' href='/favicon.svg' />
      </Head>
      <nav>
        <div className='logo'>
          <Image src='/omencss.svg' alt='OmenCSS Logo' width={100} height={20} id='logo' />
        </div>
      </nav>
      <main className='hero'>
        <div className='center'>
          <h1 className='slide-top'>Writing CSS reimagined</h1>
        </div>
        <div className='bubbles'>
          <div className='bubble' />
          <div className='bubble' />
          <div className='bubble' />
        </div>
      </main>
    </>
  )
}
